### ISSUE TITLE
The data problem of some provinces and cities

### ISSUE THREAD

**Issue by rezakiamanesh** [hamidrezaramzani/iran-locations-api#5]
Hello
Some cities and provinces have a wrong geographical location
For example: Hormozgan province

Also, the characters of cities and provinces are in Arabic, which when used while coding, the programmer may not notice this issue due to the large size of data.

**Comment by hamidrezaramzani** [comment]
> ello Some cities and provinces have a wrong geographical location For example: Hormozgan province
> 
> Also, the characters of cities and provinces are in Arabic, which when used while coding, the programmer may not notice this issue due to the large size of data.

Thank you for bringing this issue to our attention. I appreciate your diligence in identifying the incorrect geographical locations and the use of Arabic characters in the city and province names.

I am currently working on fixing these issues and will ensure they are resolved as soon as possible. Your feedback is invaluable in helping us improve the quality of our repository.

Thanks again for your contribution!
